apiVersion: v1
kind: Service
metadata:
  name: {{ include "tspa-ui.fullname" . }}
  labels:
    {{- include "tspa-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "tspa-ui.selectorLabels" . | nindent 4 }}