name: Docker and Helm

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  actions: write
  
jobs:
  dockerbuild-tspa:
    uses: eclipse-xfsc/dev-ops/.github/workflows/dockerbuild.yml@main
    secrets: inherit
    with: 
      harbor_config: "deployment/harbor.config"
      repo_name: tspa-service
  helm-tspa:
    uses: eclipse-xfsc/dev-ops/.github/workflows/helm.yml@main
    secrets: inherit
    with: 
      buildContext:  "deployment/helm/tspa-service"
      harbor_config: "deployment/harbor.config"
  dockerbuild-ui:
    uses: eclipse-xfsc/dev-ops/.github/workflows/dockerbuild.yml@main
    secrets: inherit
    with: 
      dockerfile: ui/Dockerfile
      buildContext: ui
      harbor_config: "deployment/harbor.config"
      repo_name: tspa-ui
  helm-ui:
    uses: eclipse-xfsc/dev-ops/.github/workflows/helm.yml@main
    secrets: inherit
    with: 
      buildContext:  "deployment/helm/ui"
      harbor_config: "deployment/harbor.config"
