name: Prebuild and Build UI

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  checkout:
    name: Checkout Repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  cache-npm:
    name: Cache NPM
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/cache@v4
        with:
          path: .npm/
          key: ${{ github.ref_name }}

  prebuild-ui:
    name: Prebuild UI
    runs-on: ubuntu-latest
    needs: cache-npm
    container: node:18
    steps:
      - run: |
          cd ui
          npm ci --cache ../.npm --prefer-offline
          npm run build
      - name: Upload UI Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ui-dist
          path: ui/dist/

  license-check-ui:
    name: License Check UI
    runs-on: ubuntu-latest
    needs: cache-npm
    container: node:18
    steps:
      - run: |
          cd ui
          npm ci --cache ../.npm --prefer-offline
          npm run license:scan
      - name: Upload License Artifact
        uses: actions/upload-artifact@v4
        with:
          name: third-party-licenses
          path: ui/THIRD-PARTY.txt

  build-ui-image:
    uses: eclipse-xfsc/dev-ops/.github/workflows/dockerbuild.yml@main
